name: firecrawl
region: nyc
services:
  - name: api
    git:
      branch: main
      repo_clone_url: https://github.com/ducngfi/firecrawl
    build_command: pnpm install
    run_command: pnpm run start:production
    envs:
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: PLAYWRIGHT_MICROSERVICE_URL
        value: ${PLAYWRIGHT_MICROSERVICE_URL}
      - key: PORT
        value: "3002"
      - key: HOST
        value: "0.0.0.0"
      - key: USE_DB_AUTHENTICATION
        value: ${USE_DB_AUTHENTICATION}
      - key: NUM_WORKERS_PER_QUEUE
        value: ${NUM_WORKERS_PER_QUEUE}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: MODEL_NAME
        value: ${MODEL_NAME}
      - key: LOGGING_LEVEL
        value: ${LOGGING_LEVEL}
    http_port: 3002
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: playwright-service
    git:
      branch: main
      repo_clone_url: https://github.com/ducngfi/firecrawl
    dockerfile_path: apps/playwright-service/Dockerfile
    envs:
      - key: PORT
        value: "3000"
      - key: BLOCK_MEDIA
        value: "true"
      - key: PROXY_SERVER
        value: ${PROXY_SERVER}
      - key: PROXY_USERNAME
        value: ${PROXY_USERNAME}
      - key: PROXY_PASSWORD
        value: ${PROXY_PASSWORD}
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: worker
    git:
      branch: main
      repo_clone_url: https://github.com/ducngfi/firecrawl
    build_command: pnpm install
    run_command: pnpm run workers
    envs:
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: PLAYWRIGHT_MICROSERVICE_URL
        value: ${PLAYWRIGHT_MICROSERVICE_URL}
      - key: USE_DB_AUTHENTICATION
        value: ${USE_DB_AUTHENTICATION}
      - key: NUM_WORKERS_PER_QUEUE
        value: ${NUM_WORKERS_PER_QUEUE}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: MODEL_NAME
        value: ${MODEL_NAME}
      - key: LOGGING_LEVEL
        value: ${LOGGING_LEVEL}
      - key: HOST
        value: "0.0.0.0"
    instance_count: 1
    instance_size_slug: basic-xxs

databases:
  - engine: REDIS
    name: redis
    version: "6"